### ISSUE TITLE
NodeInvocationException: Cannot read property 'getCurrentStack' of undefined

### ISSUE THREAD

**Issue by yuxinbo** [NickMaev/react-core-boilerplate#13]
I downloaded the latest 1.7.1, after run npm i and npm run build:prod, I couldn't run TypeScript app successfully.

I tried in node.js 10 and 12 version.

The error message: An unhandled exception occurred while processing the request.

NodeInvocationException: Cannot read property 'getCurrentStack' of undefined
TypeError: Cannot read property 'getCurrentStack' of undefined
at pushCurrentDebugStack (webpack-internal:///./node_modules/@hot-loader/react-dom/cjs/react-dom-server.node.development.js:2561:56)
at ReactDOMServerRenderer.read (webpack-internal:///./node_modules/@hot-loader/react-dom/cjs/react-dom-server.node.development.js:3156:11)
at renderToString (webpack-internal:///./node_modules/@hot-loader/react-dom/cjs/react-dom-server.node.development.js:3646:27)
at renderApp (webpack-internal:///./ClientApp/boot-server.tsx:28:504)
at eval (webpack-internal:///./ClientApp/boot-server.tsx:28:581)
at new Promise (<anonymous>)
at eval (webpack-internal:///./ClientApp/boot-server.tsx:23:829)
at C:\Users\YUXB\source\repos\react-core-boilerplate-master\RCB.TypeScript\ClientApp\dist\vendor.js:1:811947
at C:\Users\YUXB\source\repos\react-core-boilerplate-master\RCB.TypeScript\ClientApp\dist\vendor.js:1:813369
at bound (domain.js:422:14)
Microsoft.AspNetCore.NodeServices.HostingModels.HttpNodeInstance.InvokeExportAsync<T>(NodeInvocationInfo invocationInfo, CancellationToken cancellationToken)

**Comment by NickMaev** [comment]
`getCurrentStack` error can be caused by trying to run the project in development mode when it was compiled in production mode.
![image](https://user-images.githubusercontent.com/13121346/63932611-336d8f00-ca60-11e9-8993-8ec012ae8302.png)

**Solution:**
1. Close IDE and stop the server app (IIS/Kestrel). 
2. Run `npm run build:dev` in the project's dir. 
3. Instead of IIS Express choose the project's name in VS panel. 
![image](https://user-images.githubusercontent.com/13121346/63932938-edfd9180-ca60-11e9-87b7-f2e283282e7c.png)
4. Run the project. It will be run in Windows Console (Kestrel), not with IIS Express.

**Comment by yuxinbo** [comment]
Thanks NickMaev. Really appreciate for the detail explanation.

**Comment by NickMaev** [comment]
Did it help you?

**Comment by yuxinbo** [comment]
I build with npm run build:dev, it works for me. Needn't change debug option from IISExpress to project name. 

Really help me.
