### ISSUE TITLE
Use of <Redirect> outside a <Router>

### ISSUE THREAD

**Issue by bjsafdie** [NickMaev/react-core-boilerplate#6]
Environment:  
* Windows 10
* Node 10.15.1
* Visual Studio 2017 v 15.9.9
* .NET Core 2.2.105

I got the template installed and building (both from "npm run build: dev" and in VS),  When I run the app,  I get the following exception:

    Microsoft.AspNetCore.NodeServices.HostingModels.NodeInvocationException: You should not use <Redirect> outside a <Router>
    Invariant Violation: You should not use <Redirect> outside a <Router>
        at invariant (webpack://%5Bname%5D_%5Bhash%5D/./node_modules/invariant/invariant.js?:40:15)
        at Object.eval [as children] (webpack://%5Bname%5D_%5Bhash%5D/./node_modules/react-router/Redirect.js?:81:50)
        at ReactDOMServerRenderer.render (webpack://%5Bname%5D_%5Bhash%5D/./node_modules/react-dom/cjs/react-dom-server.node.development.js?:3292:55)
        at ReactDOMServerRenderer.read (webpack://%5Bname%5D_%5Bhash%5D/./node_modules/react-dom/cjs/react-dom-server.node.development.js?:3059:29)
        at renderToString (webpack://%5Bname%5D_%5Bhash%5D/./node_modules/react-dom/cjs/react-dom-server.node.development.js?:3526:27)
        at renderApp (Z:\src\React Core Boilerplate1\React Core Boilerplate1\ClientApp\dist\main-server.js:158:496)
        at Z:\src\React Core Boilerplate1\React Core Boilerplate1\ClientApp\dist\main-server.js:158:504
        at new Promise (<anonymous>)
        at Z:\src\React Core Boilerplate1\React Core Boilerplate1\ClientApp\dist\main-server.js:153:800
        at eval (webpack://%5Bname%5D_%5Bhash%5D/./node_modules/aspnet-prerendering/Prerendering.js?:37:35)
       at Microsoft.AspNetCore.NodeServices.HostingModels.HttpNodeInstance.InvokeExportAsync[T](NodeInvocationInfo invocationInfo, CancellationToken cancellationToken)
       at Microsoft.AspNetCore.NodeServices.HostingModels.OutOfProcessNodeInstance.InvokeExportAsync[T](CancellationToken cancellationToken, String moduleName, String exportNameOrNull, Object[] args)
       at Microsoft.AspNetCore.NodeServices.NodeServicesImpl.InvokeExportWithPossibleRetryAsync[T](String moduleName, String exportedFunctionName, Object[] args, Boolean allowRetry, CancellationToken cancellationToken)
       at Microsoft.AspNetCore.NodeServices.NodeServicesImpl.InvokeExportWithPossibleRetryAsync[T](String moduleName, String exportedFunctionName, Object[] args, Boolean allowRetry, CancellationToken cancellationToken)
       at AspNetCore.Views_Main_Index.ExecuteAsync() in Z:\src\React Core Boilerplate1\React Core Boilerplate1\Views\Main\Index.cshtml:line 7
       at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
       at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
       at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
       at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
       at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ActionContext actionContext, IView view, ViewDataDictionary viewData, ITempDataDictionary tempData, String contentType, Nullable`1 statusCode)
       at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
       at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
       at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultAsync(IActionResult result)
       at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResultFilterAsync[TFilter,TFilterAsync]()
       at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)
       at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
       at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultFilters()
       at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
       at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
       at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
       at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
       at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
       at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
       at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
       at Microsoft.AspNetCore.SpaServices.Webpack.ConditionalProxyMiddleware.Invoke(HttpContext context)
       at Microsoft.AspNetCore.SpaServices.Webpack.ConditionalProxyMiddleware.Invoke(HttpContext context)
       at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

I get this error whether I run the app through IIS Express or from the "MyProject" debug profile (runs in console).

I am very much a noob at this, so I don't know if it is relevant, but I could never resolve this issue from the npm install:

`npm WARN connected-react-router@6.2.2 requires a peer of react-router@^4.3.1 but none is installed. You must install peer dependencies yourself.`

It appears that react-router@4.4.0-beta.1 as configured in package.json does not fulfill the dependency for connected-react-router. Trying to change the versions to get it working always seemed to invalidate some other dependency.  Nonetheless, connected-react-router is present in node-modules. This may be unrelated.

Any idea why I am getting this error?

**Comment by NickMaev** [comment]
Hello @bjsafdie,
Thanks for using React Core Boilerplate!
Please, try to update it to v. 1.6.2. It should work properly now.

**Comment by NickMaev** [comment]
Hello @bjsafdie
Is it OK now?
